[build]
  base = "frontend"
  command = "npm install && ng build --configuration production"
  publish = "dist/kanban-board"

# Configurações de redirecionamento para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Not = [IsFile]}

# Configurações de headers para segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Variáveis de ambiente para produção
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  ANGULAR_APP_API_URL = "https://kanban-deploy-fmfj.onrender.com" 