services:
  # Backend service (Node.js)
  - type: web
    name: kanban-deploy-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: FIREBASE_PROJECT_ID
        fromDatabase:
          name: kanban-deploy-envs
          property: FIREBASE_PROJECT_ID
      - key: FIREBASE_CLIENT_EMAIL
        fromDatabase:
          name: kanban-deploy-envs
          property: FIREBASE_CLIENT_EMAIL
      - key: FIREBASE_PRIVATE_KEY
        fromDatabase:
          name: kanban-deploy-envs
          property: FIREBASE_PRIVATE_KEY
    autoDeploy: true

  # Frontend service (Static)
  - type: web
    name: kanban-deploy-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist/kanban-board
    envVars:
      - key: ANGULAR_APP_API_URL
        value: https://kanban-deploy-backend.onrender.com
      - key: ANGULAR_APP_FIREBASE_API_KEY
        fromDatabase:
          name: kanban-deploy-envs
          property: FIREBASE_API_KEY
      - key: ANGULAR_APP_FIREBASE_AUTH_DOMAIN
        fromDatabase:
          name: kanban-deploy-envs
          property: FIREBASE_AUTH_DOMAIN
      - key: ANGULAR_APP_FIREBASE_PROJECT_ID
        fromDatabase:
          name: kanban-deploy-envs
          property: FIREBASE_PROJECT_ID
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true

databases:
  - name: kanban-deploy-envs
    databaseName: envs
    user: kanban

# Configuração de redirecionamento
# Qualquer acesso a https://kanban-deploy.onrender.com será redirecionado para o frontend
redirects:
  - source: /*
    destination: https://kanban-deploy-frontend.onrender.com
    type: permanent 